### PR TITLE
Add turkish translations

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by msasikanth** [comment]
Please run code formatting using `gradle spotlessApply`

**Comment by mikropsoft** [comment]
@msasikanth Can you tell me how to do that? I don't understand exactly what you mean.

**Comment by msasikanth** [comment]
> @msasikanth Can you tell me how to do that? I don't understand exactly what you mean.

If you opened the project in Android Studio. You can run a Gradle command by pressing `ctrl` twice and typing `gradle spotlessApply`. That should format the project

https://www.jetbrains.com/help/idea/running-anything.html#running_app

**Comment by msasikanth** [comment]
I will merge this in first and format the code later. Thanks for the translations 🙌🏾

**Pull request merged**
