### PR TITLE
Fix featured section background size on android devices with api level 30 or below

### PR DESCRIPTION
**Pull request by darktiny**
Screenshot_20230918_161213

### CODE REVIEW

**Comment by msasikanth** [comment]
Oh, good catch. Thanks for raising a PR. That particular variable is for image based aspect ratio and isn't for gradient based one. Please create a new variable that will change the aspect ratio for gradient background, I will get the other two values for different window sizes.

**Comment by darktiny** [comment]
@msasikanth Updated

**Comment by msasikanth** [comment]
> @msasikanth Updated

Please set these as values for the gradient background

```kt
when (LocalWindowSizeClass.current.widthSizeClass) {
  WindowWidthSizeClass.Compact -> 0.8f
  WindowWidthSizeClass.Medium -> 1.11f
  WindowWidthSizeClass.Expanded -> 2.3f
  else -> 0.8f
}
```

**Comment by darktiny** [comment]
@msasikanth Updated

**Comment by msasikanth** [comment]
> @msasikanth Updated

You updated the wrong values. We need to use these for the `featuredGradientBackgroundAspectRatio` variable that you created.

**Comment by darktiny** [comment]
@msasikanth Sorry for that, Updated

**Pull request merged**
